#version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bi_postgres
    environment:
      POSTGRES_USER: bi
      POSTGRES_PASSWORD: bi
      POSTGRES_DB: ntpd
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bi_network

  metabase:
    image: metabase/metabase:latest
    container_name: bi_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - bi_network

volumes:
  pgdata:

networks:
  bi_network: